# Generated by Django 3.2.6 on 2021-08-08 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostData',
            fields=[
                ('procedure_source', models.CharField(blank=True, db_column='Procedure_Source', max_length=225, null=True)),
                ('procedure_id', models.CharField(db_column='Procedure_ID', max_length=225)),
                ('procedure_cost', models.CharField(blank=True, db_column='Procedure_Cost', max_length=225, null=True)),
                ('facility_procedure_id', models.CharField(db_column='Facility_Procedure_ID', max_length=225, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=225, null=True)),
                ('year', models.CharField(db_column='Year', max_length=45)),
                ('index', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'cost_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HospitalData',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('facility_id', models.TextField(blank=True, db_column='Facility_ID')),
                ('facility_name', models.CharField(blank=True, db_column='Facility_Name', max_length=80, null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('city', models.TextField(blank=True, db_column='City', null=True)),
                ('state', models.TextField(blank=True, db_column='State', null=True)),
                ('zip_code', models.BigIntegerField(blank=True, db_column='ZIP_Code', null=True)),
                ('county_name', models.TextField(blank=True, db_column='County_Name', null=True)),
                ('phone_number', models.TextField(blank=True, db_column='Phone_Number', null=True)),
                ('hospital_type', models.TextField(blank=True, db_column='Hospital_Type', null=True)),
                ('hospital_ownership', models.TextField(blank=True, db_column='Hospital_Ownership', null=True)),
                ('emergency_services', models.TextField(blank=True, db_column='Emergency_Services', null=True)),
                ('meets_criteria_for_promoting_interoperability_of_ehrs', models.TextField(blank=True, db_column='Meets_criteria_for_promoting_interoperability_of_EHRs', null=True)),
                ('hospital_overall_rating', models.TextField(blank=True, db_column='Hospital_Overall_Rating', null=True)),
                ('mortality_national_comparison', models.TextField(blank=True, db_column='Mortality_National_Comparison', null=True)),
                ('safety_of_care_national_comparison', models.TextField(blank=True, db_column='Safety_of_Care_National_Comparison', null=True)),
                ('readmission_national_comparison', models.TextField(blank=True, db_column='Readmission_National_Comparison', null=True)),
                ('patient_experience_national_comparison', models.TextField(blank=True, db_column='Patient_Experience_National_Comparison', null=True)),
                ('effectiveness_of_care_national_comparison', models.TextField(blank=True, db_column='Effectiveness_of_Care_National_Comparison', null=True)),
                ('timeliness_of_care_national_comparison', models.TextField(blank=True, db_column='Timeliness_of_Care_National_Comparison', null=True)),
                ('efficient_use_of_medical_imaging_national_comparison', models.TextField(blank=True, db_column='Efficient_Use_of_Medical_Imaging_National_Comparison', null=True)),
            ],
            options={
                'db_table': 'hospital_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('submission_id', models.BigIntegerField(db_column='submission_id', primary_key=True, serialize=False)),
                ('insurance_provider', models.CharField(blank=True, db_column='insurance_provider', max_length=100, null=True)),
                ('insurance_subplan', models.CharField(blank=True, db_column='insurance_subplan', max_length=100, null=True)),
                ('procedure_cost', models.FloatField(db_column='procedure_cost')),
                ('timestamp', models.DateTimeField(db_column='timestamp', default=django.utils.timezone.now)),
                ('cost', models.ForeignKey(blank=True, db_column='cost', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.costdata')),
                ('hospital', models.ForeignKey(blank=True, db_column='hospital', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hospitaldata')),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procedure_submissions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
